-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."event_files" add column "createdAt" timestamptz
--  not null default now();
