dev:
  deploy:
    parameters:
      stack_name: ralens-dev
      resolve_s3: true
      s3_prefix: ralens-dev
      region: eu-central-1
      confirm_changeset: true
      capabilities: CAPABILITY_IAM
      image_repositories: []
      parameter_overrides: ["Environment=dev","Stage=ralens-dev"]

prod:
  deploy:
    parameters:
      stack_name: ralens-prod
      resolve_s3: true
      s3_prefix: ralens-prod
      region: eu-central-1
      confirm_changeset: true
      capabilities: CAPABILITY_IAM
      image_repositories: []
      parameter_overrides: ["Environment=prod","Stage=ralens"]

version: 0.1
