name: Deploy web app to Preview Channel

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "apps/web/**"
      - "packages/react/**"
      - ".github/workflows/deploy-web-preview.yml"

jobs:
  # Build & Test
  buildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 6.22.2

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"

      # Install
      - name: INSTALL
        run: pnpm install

      # Build
      - name: BUILD
        run: pnpm build:web
        env:
          VITE_FIREBASE_CONFIG: ${{ secrets.VITE_FIREBASE_CONFIG_DEV }}

      # Test
      - name: TEST
        run: pnpm test:web:ci

      # Upload dist artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: web-dist
          path: apps/web/dist/

      # Upload coverage artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: web-coverage
          path: apps/web/coverage/lcov.info

  coverage:
    name: Coverage analysis
    needs: buildAndTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Donwload coverage artifacts
      - uses: actions/download-artifact@v3
        with:
          name: web-coverage

      # Update coverage file to codecov
      - name: CODECOV
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info

  # Deploy
  deploy:
    # Ronly run when pr is ready for review
    if: ${{ !github.event.pull_request.draft }}
    name: Deploy
    runs-on: ubuntu-latest
    needs: buildAndTest
    steps:
      - uses: actions/checkout@v3

      # Donwload coverage artifacts
      - uses: actions/download-artifact@v3
        with:
          name: web-dist
          path: apps/web/dist

      - name: Deploy to Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PREVEZIC }}'
          projectId: prevezic
