name: Deploy Nhost Dev

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force deploy'
        required: false
        type: boolean
        default: false
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "nhost/**"

jobs:
  changes:
    name: 📂 Check for changes
    runs-on: ubuntu-latest
    outputs:
      shouldRun: ${{ steps.filter.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v37
        id: filter
        with:
          since_last_remote_commit: true
          files: |
            nhost/**

  deploy:
    name: 🚀 Deploy to Nhost
    needs: changes
    if: needs.changes.outputs.shouldRun == 'true' || inputs.force == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'nhost'
          push: origin deploy_dev --set-upstream --force
          message: "[nhost] Deploy ${{ github.event.pull_request.head.ref }} to Ralens Dev"
          committer_name: GitHub Actions
          committer_email: actions@github.com
