name: Deploy Firebase Functions to Dev

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "apps/functions/**"
      - ".github/workflows/deploy-functions-dev.yml"

jobs:
  build:
    name: Build Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 6.22.2

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"

      # Install
      - name: INSTALL
        run: pnpm install

      # Build
      - name: BUILD
        run: pnpm build:functions

      # Upload dist artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: functions-dist
          path: apps/functions/dist/

  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 6.22.2

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"

      # Donwload dist artifacts
      - uses: actions/download-artifact@v3
        with:
          name: functions-dist
          path: apps/functions/dist

      # Install
      - name: Install Firebase CLI
        run: pnpm add -g firebase-tools

      - name: Create env file
        run: |
          cd apps/functions
          touch .env
          echo SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY_DEV }} >> .env
          cat .env

      - name: Deploy to prevezic-dev
        run: |
          firebase use prevezic-dev
          cd apps/functions
          pnpm remove -D @prevezic/tsconfig eslint-config-prevezic-ts
          pnpm deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
